<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cat [
  <!ELEMENT cat ( head, ( file+ | cat+ ) )>
  <!ATTLIST cat
    xml:id ID #REQUIRED 
   >
  <!-- 
<book> : un livre dans un corpus

  -->
  <!ELEMENT file ( subject* )>
  <!ATTLIST file
    href CDATA #REQUIRED 
   >
  <!ELEMENT subject EMPTY>
  <!ATTLIST subject
    field CDATA #REQUIRED 
   >
  <!ELEMENT head ( #PCDATA | i | sc | sup )*>
  <!ELEMENT i ( #PCDATA | sup )*>
  <!ELEMENT sup ( #PCDATA )*>
  <!ELEMENT sc ( #PCDATA | sup )*>
]>
<cat xml:id="critique">
  <head>La critique et ses sources intellectuelles</head>
  <cat xml:id="esthetique">
    <head>Critique</head>
    <cat xml:id="theorie">
      <head>Théorie littéraire et esthétique</head>
      <file href="becq-de-fouquieres_art-mise-en-scene"/>
      <file href="chamfort_ebauches"/>
      <file href="crevel_esprit-contre-raison"/>
      <file href="deschanel_physiologie"/>
    </cat>
    <cat xml:id="critlitt">
      <head>Critique et histoire littéraire</head>
      <file href="albalat_mal-decrire-roman-contemporain"/>
      <file href="albalat_formation"/>
      <file href="albalat_ennemis"/>
      <file href="albalat_souvenirs"/>
      <file href="albalat_comment"/>
      <file href="asselineau_roman-bourgeois-preface"/>
      <file href="auguis_chamfort-notice"/>
      <file href="barbey-aurevilly_romanciers"/>
      <file href="barbey-aurevilly_goethe-diderot"/>
      <file href="barbey-aurevilly_poesie"/>
      <file href="barbey-aurevilly_voyageurs-et-romanciers"/>
      <file href="barbey-aurevilly_philosophes"/>
      <file href="barbey-aurevilly_litterature-etrangere"/>
      <file href="barine_musset"/>
      <file href="barres_taine"/>
      <file href="bazalgette_esprit"/>
      <file href="beaunier_poesie"/>
      <file href="bourget_etudes1"/>
      <file href="bourget_etudes3"/>
      <file href="bourget_pages-de-critique"/>
      <file href="bourget_temoignages"/>
      <file href="bourget_temoignages-2"/>
      <file href="bremond_poesie-pure"/>
      <file href="brunetiere_etudes-critiques-01"/>
      <file href="brunetiere_études-critiques-02"/>
      <file href="brunetiere_roman-naturaliste"/>
      <file href="brunetiere_banqueroute-du-naturalisme"/>
      <file href="brunetiere_etudes-critiques-03"/>
      <file href="brunetiere_nouvelles-questions-critique"/>
      <file href="brunetiere_science-et-religion"/>
      <file href="brunetiere_metaphysique-positiviste"/>
      <file href="brunetiere_evolution-des-genres"/>
      <file href="caro_sand"/>
      <file href="charpentier-paul_mal-du-siecle"/>
      <file href="crevel_clavecin-diderot"/>
      <file href="daudet-leon_stupide19e"/>
      <file href="deschanel_romantisme"/>
      <file href="des-essarts_portraits-de-maitres"/>
      <file href="doumic_ecrivains"/>
      <file href="doumic_jeunes"/>
      <file href="du-bos_approximations2"/>
      <file href="dubos_critiques"/>
      <file href="du-casse_histoire-anecdotique-01"/>
      <file href="dupuy_poetes-et-critiques"/>
      <file href="equilbecq_litterature-merveilleuse-des-noirs"/>
    </cat>
    <cat xml:id="critart">
      <head>Critique et histoire artistique</head>
      <file href="revue-wagnerienne_tome1"/>
      <file href="baudelaire_curiosites-esthetiques"/>
      <file href="bazalgette_esprit"/>
      <file href="diderot_salon1759"/>
      <file href="diderot_salon1761"/>
      <file href="diderot_salon1763"/>
      <file href="diderot_essais-peinture1765"/>
      <file href="diderot_salon1767"/>
      <file href="dubos_critiques"/>
    </cat>
    <cat xml:id="rhetorique">
      <head>Rhétorique</head>
      <file href="dumarsais_tropes"/>
    </cat>
    <cat xml:id="pers">
      <head>Écrits intimes et correspondances</head>
      <file href="bashkirtseff_lettres"/>
    </cat>
  </cat>
  <cat xml:id="philosophie">
    <head>Philosophie</head>
    <file href="bergson_conscience"/>
    <file href="bergson_matiere"/>
    <file href="bergson_rire"/>
    <file href="bergson_evolution"/>
    <file href="bergson_france"/>
    <file href="bergson_energie"/>
    <file href="bergson_duree"/>
    <file href="bergson_sources"/>
    <file href="bergson_pensee"/>
    <file href="carrau_articles"/>
    <file href="comte_cours-philo-positive"/>
    <file href="comte_discours-esprit-positif"/>
  </cat>
  <cat xml:id="shs">
    <head>Sciences humaines et sociales</head>
    <cat xml:id="histoire">
      <head>Histoire</head>
      <file href="bazalgette_latin"/>
      <file href="diderot_claude-neron"/>
    </cat>
    <cat xml:id="politique">
      <head>Politique</head>
      <file href="barres_familles"/>
      <file href="bazalgette_esprit"/>
      <file href="bazalgette_latin"/>
      <file href="diderot_plan-universite"/>
    </cat>
    <cat xml:id="religion">
      <head>Religion</head>
    </cat>
    <cat xml:id="sociologie">
      <head>Sociologie</head>
      <file href="bougle_idees_egalitaires"/>
      <file href="durkheim_cours-de-philosophie"/>
      <file href="durkheim_empirisme-rationaliste-de-taine"/>
      <file href="durkheim_jugements-de-valeur"/>
    </cat>
    <cat xml:id="ethnologie">
      <head>Ethnologie</head>
    </cat>
    <cat xml:id="psychologie">
      <head>Psychologie</head>
      <file href="egger_parole"/>
    </cat>
    <cat xml:id="economie">
      <head>Économie</head>
    </cat>
    <cat xml:id="shsdivers">
      <head>Divers</head>
    </cat>
  </cat>
  <cat xml:id="sciences">
    <head>Sciences exactes</head>
    <cat xml:id="logicomath">
      <head>Sciences formelles</head>
      <cat xml:id="logique">
        <head>Logique</head>
      </cat>
      <cat xml:id="mathematiques">
        <head>Mathématiques</head>
      </cat>
    </cat>
    <cat xml:id="matiere">
      <head>Matière</head>
      <cat xml:id="physique">
        <head>Physique</head>
      </cat>
      <cat xml:id="chimie">
        <head>Chimie</head>
      </cat>
      <cat xml:id="astronomie">
        <head>Astronomie</head>
      </cat>
    </cat>
    <cat xml:id="vie">
      <head>Sciences de la vie</head>
      <cat xml:id="medecine">
        <head>Médecine</head>
        <file href="bernard_lecons-physio-experimentale"/>
        <file href="bernard_lecons-physio-experimentale-II"/>
        <file href="bernard_introduction-medecine-experimentale"/>
        <file href="bernard_articles"/>
      </cat>
      <cat xml:id="physiologie">
        <head>Physiologie</head>
        <file href="bernard_lecons-phenomenes-vie-I"/>
      </cat>
      <cat xml:id="biologie">
        <head>Biologie</head>
        <file href="darwin_origine-des-especes"/>
      </cat>
      <cat xml:id="geologie">
        <head>Géologie</head>
      </cat>
      <cat xml:id="botanique">
        <head>Botanique</head>
      </cat>
      <cat xml:id="zoologie">
        <head>Zoologie</head>
      </cat>
    </cat>
  </cat>
</cat>