=== OBVIL/critique/revue-wagnerienne/revue_wagnerienne_tome2/notes.dtd
<!ELEMENT notes (note+)>
<!ATTLIST notes
  xml:lang CDATA #REQUIRED
  xmlns CDATA #FIXED "http://www.tei-c.org/ns/1.0"
 >
<!ELEMENT note ( #PCDATA | hi | surname | num | p | quote )*>
<!ATTLIST note
  n CDATA #REQUIRED
 >
<!ELEMENT quote ( p | said )+>
<!ELEMENT said ( #PCDATA | hi| surname | num )*>
<!ELEMENT p ( #PCDATA | hi| surname | num )*>
<!ATTLIST p
  rend (i|center) #IMPLIED
 >
<!ELEMENT hi ( #PCDATA | surname )*>
<!ATTLIST hi
  rend (i|sup) #REQUIRED
 >
<!ELEMENT num ( #PCDATA | hi )*>
<!ELEMENT surname (#PCDATA)>
<!ATTLIST surname
  rend (sc) #IMPLIED
>

=== OBVIL/critique/du-bos/du-bos_approximations1/du-bos_approximations1_nde.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notes SYSTEM "notes.dtd">
<notes xml:lang="fr">
  <note n="$1$">L'article, rédigé entre janvier et mars 1920, est d’abord publié dans <hi rend="i">La Nouvelle Revue française</hi>, n° 80, mai 1920, p. 675-699. Les idées essentielles sont déjà présentes dans le <hi rend="i">Journal</hi> de Du Bos les 3, 4, 7, 12, 14, 15, 18 et 19 mars 1920 : <hi rend="i">Journal - 1920-1925</hi>, Préface et avant-propos de Louis Mouton, Paris, Buchet-Chastel, 2003, p. 27-37. NdE</note>
  <note n="$2$">Paul Valéry a écrit <hi rend="i">Introduction à la méthode de Léonard de Vinci</hi> en 1894. L'article paraît d’abord dans la <hi rend="i">Nouvelle Revue</hi>, Paris, t. 95, 1895, p. 742-770 (la table des matières mentionne le titre « L'Esthétique de Léonard de Vinci ») ; précédé d’une nouvelle introduction intitulée « Note et digressions » p. 8-41, il est repris aux éditions de la <hi rend="i">Nouvelle Revue française</hi> en 1919, p. 45-100, puis dans l’édition de <hi rend="i">Variété</hi> (1924). Dans la collection de la « Bibliothèque de la Pléiade », le texte de 1894 ouvre la section « Théorie poétique et esthétique » de <hi rend="i">Variété</hi>, p. 1155-1199 ; il est suivi de « Note et digression », p. 1199-1233 : <hi rend="i">Œuvres</hi>, t. I, éd. Jean Hytier, Paris, Gallimard, coll. « Bibliothèque de la Pléiade », 1957. NdE</note>
  <note n="$3$">Antoine Rivarol (1753-1801), écrivain français, journaliste royaliste, essayiste et pamphlétaire fut considéré par Chênedollé (1769-1833) comme le « dieu de la conversation ». Le jeune admirateur a retranscrit l’une des improvisations de son maître dans <hi rend="i">Ma première visite à Rivarol</hi>. Sainte-Beuve la cite dans son étude sur Chênedollé (<hi rend="i">Revue des Deux Mondes</hi>, 1er juin 1849, p. 717-771), reproduites en annexe de <hi rend="i">Chateaubriand et son groupe littéraire sous l’Empire</hi> (t. II, Garnier, 1861, p. 158-182). NdE</note>
  <note n="$4$">Albert Thibaudet, <hi rend="i">La Poésie de Stéphane Mallarmé</hi>, Paris, Tel-Gallimard, 2006, p. 417. NdE</note>
  <note n="$5$">Bourdaloue (1632-1704) jésuite français, brillant prédicateur, ce qui lui valut de prêcher à la Cour. NdE</note>
  <note n="$6$"><p><hi rend="i">Introduction à la méthode de Léonard de Vinci, op. cit.</hi>, p. 1160. NdE</p></note>
  <note n="$7$">« La Soirée avec Monsieur Teste », <hi rend="i">Monsieur Teste</hi>, in <hi rend="i">Œuvres</hi>, t. II, éd. Jean Hytier, Paris, Gallimard, coll. « Bibliothèque de la Pléiade, 1960, p. 17. NdE</note>
  <note n="$8$"><hi rend="i">Introduction à la méthode de Léonard de Vinci, op. cit.</hi>, p. 1161. NdE</note>
  <note n="$9$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1217. NdE</note>
  <note n="$10$"><hi rend="i">Ibid</hi>., p. 1215-1216. NdE</note>
  <note n="$11$"><hi rend="i">Ibid</hi>., p. 1218. NdE</note>
  <note n="$12$"><hi rend="i">Ibid</hi>., p. 1225. NdE</note>
  <note n="$13$"><hi rend="i">Ibid</hi>., p. 1219. NdE</note>
  <note n="$14$"><hi rend="i">Ibid</hi>., p. 1226. NdE</note>
  <note n="$15$"><hi rend="i">Ibid</hi>., p. 1224. NdE</note>
  <note n="$16$"><hi rend="i">Ibid</hi>., p. 1225. NdE</note>
  <note n="$17$">Racine, <hi rend="i">Bajazet</hi>, Acte II, Scène 1, v. 524. NdE</note>
  <note n="$18$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1225. NdE</note>
  <note n="$19$"><hi rend="i">Ibid</hi>., p. 1215. NdE</note>
  <note n="$20$"><hi rend="i">Ibid</hi>., p. 1207. NdE</note>
  <note n="$21$"><hi rend="i">Matthieu</hi>, 5, 13. NdE</note>
  <note n="$22$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1206. NdE</note>
  <note n="$23$"><hi rend="i">Introduction à la méthode de Léonard de Vinci, op. cit.</hi>, p. 1160. NdE</note>
  <note n="$24$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1209. NdE</note>
  <note n="$25$">« Mon esprit, tu te meus avec agilité » : Baudelaire, « Élévation », <hi rend="i">Les Fleurs du mal</hi>, in <hi rend="i">Œuvres complètes I</hi>, éd. de Claude Pichois, Gallimard, coll. « Bibliothèque de la Pléiade », 1975, p. 10. NdE</note>
  <note n="$26$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1209. NdE</note>
  <note n="$27$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1210. NdE</note>
  <note n="$28$">John Keats, « Ode à une urne grecque », <hi rend="i">Les Odes</hi>, trad. de Alain Suied, Arfuyen, 2010, p. 22. NdE</note>
  <note n="$29$">Propos prêté à Gautier par les frères Goncourt, 1<hi rend="sup">er</hi> mai 1857, <hi rend="i">Journal</hi>, éd. R. Ricatte, Paris, Robert Laffont, coll. « Bouquins », 1989, t. 1, p. 254. NdE</note>
  <note n="$30$"><p>Flaubert, Préface des <hi rend="i">Denières chansons</hi> de Louis Bouilhet, Paris, Lévy, 1872. NdE</p></note>
  <note n="$31$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1205. NdE</note>
  <note n="$32$"><hi rend="i">Ibid</hi>., p. 1205. NdE</note>
  <note n="$33$"><hi rend="i">Ibid</hi>., p. 1207. NdE</note>
  <note n="$34$"><hi rend="i">Ibid</hi>., p. 1205. NdE</note>
  <note n="$35$"><hi rend="i">Introduction à la méthode de Léonard de Vinci, op. cit.</hi>, p. 1155-1156. NdE</note>
  <note n="$36$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1201-1202. NdE</note>
  <note n="$37$"><hi rend="i">Ibid</hi>., p. 1230. NdE</note>
  <note n="$38$"><hi rend="i">Introduction à la méthode de Léonard de Vinci, op. cit.</hi>, p. 1162-1163. NdE</note>
  <note n="$39$"><hi rend="i">Monsieur Teste, op. cit.</hi>, p. 17. NdE</note>
  <note n="$40$"><hi rend="i">Note et Digression, op. cit</hi>., p. 1206-1207. NdE</note>
  <note n="$41$"><hi rend="i">Monsieur Teste, op. cit.</hi>, p. 17. NdE</note>
  <note n="$42$"><hi rend="i">Note et Digression, op. cit.</hi>, p. 1209. NdE</note>
  <note n="$43$">Article rédigé en déc. 1920, prévu pour la revue roumaine <hi rend="i">Dimineatza</hi>. Il n’y aura pas de pré-publication avant <hi rend="i">Approximations</hi>, 1<hi rend="sup">ère</hi> série. NdE</note>
  <note n="$44$">Alfred de Vigny, « La Maison du berger : lettre à Éva », <hi rend="i">Les Destinées</hi>, in <hi rend="i">Œuvres complètes</hi>, t. I, éd. de François Germain et André Jarry, Gallimard, coll. « Bibliothèque de la Pléiade », 1986, p. 126. NdE</note>
  <note n="$45$"><hi rend="i">Les Forces éternelles</hi>, p. 119. NdE</note>
  <note n="$46$">Début du poème « Renonciation », in <hi rend="i">Les Forces éternelles</hi>, p. 244-245. NdE</note>
  <note n="$47$">Platon, <hi rend="i">Phèdre</hi>, 245c-250a. NdE</note>
  <note n="$48$">« Aux soldats de 1917 », p. 26-30. NdE</note>
  <note n="$49$">Les Bords de Marne », p. 11. NdE</note>
  <note n="$50$"><hi rend="i">Ibid</hi>., p. 12. NdE</note>
  <note n="$51$">« Aux soldats de 1917 », p. 29. NdE</note>
  <note n="$52$">« La Noble nuit est. . . », p. 179. NdE</note>
  <note n="$53$">Nietzsche, « L'Ombre », 4<hi rend="sup">ème</hi> partie, <hi rend="i">Ainsi parlait Zarathoustra</hi>, Paris, Gallimard, coll. « folio-essais », textes et variantes établis par Giorgio Colli et Mazzino Montinari, traduit de l’allemand par Maurice de Gandillac, p. 331-332. NdE</note>
  <note n="$54$">« Tristesse de l’amour », p. 326-328. NdE</note>
  <note n="$55$">Article rédigé en déc. 1920, prévu pour la revue roumaine <hi rend="i">Dimineatza.</hi> Pas de pré-publication avant <hi rend="i">Approximations</hi> 1<hi rend="sup">ère</hi> série. Il est repris au début de l’ouvrage de Charles du Bos, <hi rend="i">Le Dialogue avec André Gide</hi>, Corrêa, 1947, p. 3-15. NdE</note>
  <note n="$56$">Saint-Evremont, « Jugement sur les sciences où peut s’appliquer un honnête homme », in <hi rend="i">Libertins du XVIIe siècle</hi>, t. 2, éd. Jacques Prévot, Paris, Gallimard, coll. « Bibliothèque de la Pléiade », 2004, p. 661. NdE</note>
  <note n="$57$">Bossuet, <hi rend="i">Le Traité du libre arbitre</hi>, chap 4, début et fin. NdE</note>
  <note n="$58$">Joseph Joubert, Lettre à madame de Beaumont du 26 août 1797, dans <hi rend="i">Lettres à Pauline de Beaumont et Louise Angélique de Vintimille</hi>, Quimper, Calligrammes, 1984.</note>
  <note n="$59$">André Gide, <hi rend="i">La Porte étroite</hi>, dans <hi rend="i">Romans et récits</hi>, t. 1, Pierre Masson éd., Paris, Gallimard, coll. « Bibliothèque de la Pléiade », 2009, p. 905. NdE</note>
  <note n="$60$"><p>Les trois études qui suivent, – « Le Courage de l’esprit », « Quelques corollaires du théorème fondamental » et « L'Observateur. Le Côté de Guermantes » – rédigées respectivement en janv. 1921, janv-fév. 1921, fév-mars 1921, étaient destinées à la revue roumaine <hi rend="i">Dimineatza</hi> qui ne les publiera pas. Considérablement corrigées et amplifiées, elles paraissent pour la première fois dans <hi rend="i">Approximations</hi>, 1<hi rend="sup">ère</hi> série. NdE</p></note>
  <note n="$61$"><hi rend="i">On ne badine pas avec l’amour</hi>, Acte II, sc. 5. NdE</note>
  <note n="$62$"><hi rend="i">Ibid</hi>., p. 176-179. NdE</note>
  <note n="$63$">Proust, « À propos du “style” de Flaubert », <hi rend="i">La NRF</hi>, n° 16, janv. 1920, p. 75 . NdE</note>
  <note n="$64$">Roman autobiographique écrit entre 1873 et 1884, publié en 1903. NdE</note>
  <note n="$65$">Walter Savage Landor, <hi rend="i">Conversations imaginaires entre Diogène et Platon</hi>, (1826), Paris, éd. Allia, 1995, p. 50. NdE</note>
  <note n="$66$"><p>Maurice Barrès, <hi rend="i">Gréco ou le secret de Tolède</hi> (1912), in <hi rend="i">Romans et Voyages</hi>, t. 2, Robert Laffont, coll. « Bouquins », 1992, p. 535. NdE</p><p>p. 115NdE</p></note>
  <note n="$67$">« Une agonie », <hi rend="i">La Nouvelle Revue française</hi>, n° 88, janv. 1921, p. 5-30 et « Un baiser », <hi rend="i">La Nouvelle Revue française</hi>, n° 89, fév. 1921, p. 129-156. NdE</note>
  <note n="$68$">Voltaire, « (Le) Dante », <hi rend="i">Dictionnaire philosophique.</hi> NdE</note>
